##### Workflows ######

name: First CI Workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      UNAME: dhananjaypuri
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Code build
        run: docker -v
      - name: Image Upload
        run: |
          docker container ls
          echo "${{ github.USERNAME }}"
          #echo ${{ github.USERNAME }} | docker login -u ${UNAME} --password-stdin
