##### Workflows ######

name: First CI Workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    env:
      UNAME: dhananjaypuri
      PASSWD: mydocker@123
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Code build
        run: docker -v
      - name: Image Upload
        run: |
          docker container ls
          echo $UNAME
          echo "$PASSWD"
          docker login -u ${UNAME} -p ${PASSWD}
