##### Workflows ######

name: First CI Workflow

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Code build
        run: echo "This will build the job"
      - name: Image Upload
        run: ls -al
